# Optional: switch Service to ClusterIP and use Ingress + ACM
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: hello-api
#   annotations:
#     kubernetes.io/ingress.class: alb
#     alb.ingress.kubernetes.io/scheme: internet-facing
# spec:
#   rules:
#     - host: hello.your-domain.com
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: hello-api
#                 port:
#                   number: 80
