apiVersion: v1
kind: Secret
metadata:
  name: hello-api-secrets
type: Opaque
stringData:
  DB_HOST: {{ .Values.env.DB_HOST | quote }}
  DB_USER: {{ .Values.env.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.env.DB_PASSWORD | quote }}
