groups:
- name: example.rules
  rules:
  - alert: HighCPUUsage
    expr: avg(rate(container_cpu_usage_seconds_total[5m])) > 0.5
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "CPU usage > 50% for 2m"
