replicaCount: 2

image:
  repository: hello-api   # change to your ECR repo if pushing remotely
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources: {}
#  requests:
#    cpu: "100m"
#    memory: "128Mi"
#  limits:
#    cpu: "500m"
#    memory: "256Mi"

env:
  APP_VERSION: "v0.1.0"
  DB_HOST: ""
  DB_USER: ""
  DB_PASSWORD: ""

probe:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10
