apiVersion: v1
kind: Service
metadata:
  name: hello-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hello-api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
